src/profiles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('me/', views.ShowProfile.as_view(), name='show_me'),
    path('signup/', views.SignupView.as_view(), name='sign_up'),
    path('<slug:slug>/', views.ShowProfile.as_view(),
         name='show_user'),
]

src/viewschapter/urls.py
from django.urls import path, include
from . import views
from . import apiviews

app_name = 'viewschapter'

blog_patterns = [
    path('', views.BlogHomeView.as_view(), name='blog_home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('<slug:slug>/', views.ArticleView.as_view(), name='article'),
]

urlpatterns = [
    path('hello-fn/<str:name>/',
         views.hello_fn, name="hello_fn_name"),
    path('hello-fn/',
         views.hello_fn, name="hello_fn"),

    path('hello-cl/<str:name>/',
         views.HelloView.as_view(), name="hello_cl_name"),
    path('hello-cl/',
         views.HelloView.as_view(), name="hello_cl"),

    path('hello-su/<str:name>/',
         views.SuperVillainView.as_view(), name="hello_su_name"),
    path('hello-su/',
         views.SuperVillainView.as_view(), name="hello_su"),

    path('myfeed/', views.MyFeed.as_view(
        extra_context={'title': 'My Feed'}), name="myfeed"),
    path('public/',
         views.PublicPostJSONView.as_view(), name="public"),

    path('year/<int:year>/',
         views.YearView.as_view(), name="year_view"),

    path('blog/', include(blog_patterns)),

    path('api/public/',
         apiviews.PublicPostList.as_view(), name="api_public"),
]

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% load staticfiles %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "includes/_brandname.html" %} :: {% endblock %}</title>

    <!-- Vendored stylesheets-->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
      <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}
  </head>

  <body class="{% block bodyclass %}{% endblock %}">




    {% block navbar %}
      <nav class="navbar sticky-top navbar-dark bg-dark navbar-expand-lg">
        <a class="navbar-brand" href="{% url 'home'%}">
          <img src="{% static 'site/img/logo.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          {% include "includes/_brandname.html" %}
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        {% if user.is_authenticated %}
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'viewschapter:myfeed' %}">My Feed</a>
                  <a class="dropdown-item" href="{% url 'show_me' %}">My Profile</a>
                  {% if user.is_staff %}
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
              </li>
            </ul>

          </div>
        {% endif %}

      </nav>
    {% endblock %}




    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}"  alert-dismissible fade show" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}




    {% block pre_content %}{% endblock %}

    <div class="container-fluid" id="maincontent">
      {% block content %}{% endblock %}
    </div><!-- /.container-fluid -->





    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
        <div class="footer">
          <div class="row">
            <div class="col-lg-6">
              <p>&copy; Company {% now 'Y' %}. Example project for a <a href="https://arunrocks.com/static/book/django-design-patterns-best-practices-2-ed/">Django book</a></p>
            </div>
            <div class="col-lg-6 text-right">
              Connect with us on our
              <a href="#"><i class="material-icons" style="font-size: 1rem">public</i> Support page</a>
            </div>
          </div>
        </div>
      </div>
    {% endblock %}





    <!-- Bootstrap core JavaScript
         ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'bootstrap/js/vendor/jquery.min.js' %}"><\/script>')</script>
    <script src="{% static 'bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'bootstrap/js/ie10-viewport-bug-workaround.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

src/templates/home.html
{% extends "base.html" %}

{% block title %} {{ block.super }} Home {% endblock %}

{% block bodyclass %}homepage{% endblock %}

{% block pre_content %}
  <div class="jumbotron jumbotron-fluid corporate-jumbo">
    <div class="container">
      <h1 class="display-3">Welcome to SuperBook!</h1>
      <p class="lead">A social network for hard working superheroes and their awesome fans.</p>
      <div class="row mt-4">
        <div class="col-sm-2">
        <a class="btn btn-primary btn-lg" href="{% url 'sign_up'%}" role="button">Join</a>
      </div>
      <div class="col-sm">
        <a class="btn btn-secondary btn-lg" href="{% url 'login'%}" role="button">Login</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}