src/profiles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('me/', views.ShowProfile.as_view(), name='show_me'),
    path('signup/', views.SignupView.as_view(), name='sign_up'),
    path('<slug:slug>/', views.ShowProfile.as_view(),
         name='show_user'),
]

src/viewschapter/urls.py
from django.urls import path, include
from . import views
from . import apiviews

app_name = 'viewschapter'

blog_patterns = [
    path('', views.BlogHomeView.as_view(), name='blog_home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('<slug:slug>/', views.ArticleView.as_view(), name='article'),
]

urlpatterns = [
    path('hello-fn/<str:name>/',
         views.hello_fn, name="hello_fn_name"),
    path('hello-fn/',
         views.hello_fn, name="hello_fn"),

    path('hello-cl/<str:name>/',
         views.HelloView.as_view(), name="hello_cl_name"),
    path('hello-cl/',
         views.HelloView.as_view(), name="hello_cl"),

    path('hello-su/<str:name>/',
         views.SuperVillainView.as_view(), name="hello_su_name"),
    path('hello-su/',
         views.SuperVillainView.as_view(), name="hello_su"),

    path('myfeed/', views.MyFeed.as_view(
        extra_context={'title': 'My Feed'}), name="myfeed"),
    path('public/',
         views.PublicPostJSONView.as_view(), name="public"),

    path('year/<int:year>/',
         views.YearView.as_view(), name="year_view"),

    path('blog/', include(blog_patterns)),

    path('api/public/',
         apiviews.PublicPostList.as_view(), name="api_public"),
]

src/posts/models.py
from django.db import models
from django.conf import settings
from .managers import PostManager


class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Postable(TimeStampedModel):
    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  blank=True,
                                  on_delete=models.CASCADE,
                                  null=True,
                                  related_name="%(class)ss")
    message = models.TextField(max_length=500)

    def __str__(self):
        return "{}: {:.30}".format(self.posted_by, self.message)

    class Meta:
        abstract = True
        ordering = ["-created"]


class Post(Postable):
    POST_PRIVACY = (
        ('public', 'Public'),
        ('individual', 'Individual')
    )
    privacy = models.CharField(max_length=12, choices=POST_PRIVACY,
                               default='public')
    # A recipient is needed if the privacy is set to "Individual"
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  on_delete=models.CASCADE,
                                  blank=True,
                                  null=True,
                                  related_name="recieved_posts")
    objects = PostManager()


class Comment(Postable):
    parent_post = models.ForeignKey(Post, on_delete=models.CASCADE)


class Like(models.Model):
    liked_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return "{} liked <{}>".format(self.liked_by, self.post)

src/viewschapter/models.py
from django.db import models

# Create your models here.

src/viewschapter/views.py
from django.http import HttpResponse, JsonResponse
from django.views.generic import View, TemplateView
from django.core.exceptions import PermissionDenied
from datetime import datetime
from posts import models


def hello_fn(request, name="World"):
    return HttpResponse("Hello {}!".format(name))


class HelloView(View):

    def get(self, request, name="World"):
        return HttpResponse("Hello {}!".format(name))


class GreetView(View):
    greeting = "Hello {}!"
    default_name = "World"

    def get(self, request, **kwargs):
        name = kwargs.pop("name", self.default_name)
        return HttpResponse(self.greeting.format(name))


class SuperVillainView(GreetView):
    greeting = "We are the future, {}. Not them. "
    default_name = "my friend"


class FeedMixin(object):
    feed_context_name = "feed"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.feed_context_name] = models.Post.objects.viewable_posts(
            self.request.user)
        return context


class LoginRequiredMixin:

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class MyFeed(LoginRequiredMixin, FeedMixin, TemplateView):
    template_name = "myfeed.html"


class PublicPostJSONView(View):

    def get(self, request, *args, **kwargs):
        msgs = models.Post.objects.public_posts().values(
            "posted_by_id", "message")[:5]
        return JsonResponse(list(msgs), safe=False)


class YearView(View):

    def get(self, request, year):
        try:
            d = datetime(year=year, month=1, day=1)
            reply = "First day of the year {} is {}!".format(
                year, d.ctime())
        except ValueError:
            reply = "Error: Invalid year!"
        return HttpResponse(reply)


class BlogHomeView(TemplateView):
    template_name = "blog_home.html"


class AboutView(TemplateView):
    template_name = "about.html"


class ArticleView(TemplateView):
    template_name = "article.html"

src/viewschapter/templates/about.html
<h1>About Us</h1>

src/viewschapter/templates/article.html
<h1>Article</h1>
<h2> Slug: {{ slug }}</h2>

src/viewschapter/templates/blog_home.html
<h1>Blog Home</h1>

src/viewschapter/templates/myfeed.html
{% extends "base.html" %}

{% block title %} {{ block.super }}My Feed {% endblock %}

{% block content %}
  <div class="row">
    <div class="col-12 col-md-3 col-xl-2 text-center left-sidebar">
      <!-- Left sidebar -->
      <img style="width: 200px; height: 200px;" src="/static/site/img/user.svg" class="rounded mx-auto d-block mt-4" alt="profile picture">
      <h1 class="display-4">{{ user.username }}</h1>
      <p class="lead">{{ user.profile.bio|default_if_none:" "|truncatechars:50 }}</p>
    </div>
    <div class="d-none d-xl-block col-xl-2 right-sidebar order-last">
      <!-- Right sidebar -->
      <p><small>Sponsored Content</small></p>
      <div style="height: 300px; background: #fff">
      </div>
    </div>
    <div class="col-12 col-md-9 col-xl-8 py-md-3 pl-md-5 feed-content">
      <!-- Middle feed -->
      <h2>{{ title }}</h2>
      {% for item in feed %}
        <div class="media mb-4" style="border: 1px solid #e4e4e4;padding: 8px;border-radius: 4px;">
          <img class="mr-3" style="width: 64px; height: 64px;" src="/static/site/img/user.svg"  alt="Profile pic">
          <div class="media-body">
            <h5 class="mt-0"><a href="{% url 'show_user' slug=item.posted_by %}">{{ item.posted_by }}</a></h5>
            {{ item.message|safe|escape }}
            <div class="post-meta mt-4">
              <p>{{ item.like_set.count }} Like{{ item.like_set.count|pluralize }} | Posted on: {{ item.modified}}</p>
            </div>
            {% for comment in item.comment_set.all %}
              <div class="media mt-3">
                <a class="pr-3" href="#">
                  <img style="width: 32px; height: 32px;" src="/static/site/img/user.svg"  alt="Profile pic">
                </a>
                <div class="media-body">
                  <b class="mt-0"><a href="{% url 'show_user' slug=comment.posted_by %}">{{ comment.posted_by }}</a></b>
                  <small>{{ comment.message|safe|escape }}</small>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}